#!/usr/bin/env sh

npx commitlint --config .commitlintrc.ts --edit "$1" ||
(
    echo '❌ Commit message format is incorrect. '
    echo 'Please run `git config --local commit.template ./.github/.gitmessage`.';
    false;
)
