#!/usr/bin/env sh

npx lint-staged ||
{
    echo 'Staged files check failed. Run npm run format, add changes and try commit again.';
    false;
}

npm run format -- --cache --cache-location '../.vscode/prettier-cache' --cache-strategy 'metadata' ||
{
    echo 'Prettier check failed. Make the required changes listed above, add changes and try the commit again.';
    false;
}

npm run lint ||
{
    echo 'ESLint check failed. Make the required changes listed above, add changes and try the commit again.'
    false;
}

npm run type-check ||
{
    echo 'Type check failed.'
    false;
}
