name: Dependency review

on:
  workflow_call:
    inputs:
      fail-on-severity:
        default: moderate
        description: 'Minimum severity to block a PR. Possible values are `low`, `moderate`, `high`, `critical`. Defaults to `moderate`.'
        required: false
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v6

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: ${{ inputs.fail-on-severity }}
          comment-summary-in-pr: true
