name: Jest

on:
  workflow_call:
    inputs:
      artifact-name:
        default: coverage
        description: 'String to name the artifact containing coverage results. Defaults to `coverage`.'
        required: false
        type: string
      artifact-source-path:
        default: './coverage/**/*.*'
        description: 'Path or glob containing the coverage results. Defaults to `./coverage/**/*.*`.'
        required: false
        type: string
      upload-coverage-artifact:
        default: true
        description: 'Boolean controlling the upload of a coverage artifact.'
        type: boolean
        required: true

jobs:
  jest:
    name: Run 'npm test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage
        id: upload-coverage
        if: ${{ inputs.upload-coverage-artifact }}
        uses: actions/upload-artifact@v6
        with:
          path: ${{ inputs.artifact-source-path }}
          retention-days: 3
          if-no-files-found: warn
          name: ${{ inputs.artifact-name }}
